version: '3'

services:
  nginx:
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
     - 80:80
   networks:
     - proxy

  app-web-blue-01:
    image: andrecostall/app-web-page:blue
    networks:
     - proxy

  app-web-blue-02:
    image: andrecostall/app-web-page:blue
    networks:
     - proxy   

  app-web-red-01:
    image: andrecostall/app-web-page:red
    networks:
     - proxy

  app-web-red-02:
    image: andrecostall/app-web-page:red
    networks:
     - proxy

networks:
  proxy:
    driver: bridge